FROM mcr.microsoft.com/devcontainers/python:1-3.9-bullseye

RUN curl https://get.modular.com | \
  MODULAR_AUTH=my_modular_auth_secret \
  sh -

RUN modular install mojo

RUN echo 'export MODULAR_HOME="$HOME/.modular"' >> ~/.bashrc
RUN echo 'export PATH="$MODULAR_HOME/pkg/packages.modular.com_mojo/bin:$PATH"' >> ~/.bashrc

RUN pip install --upgrade pip && pip install earthengine-api folium geopandas numpy opencv-python pycocotools scikit-learn scipy torch torchvision tqdm

RUN apt-get update && apt-get install ffmpeg libsm6 libxext6 libarchive-dev -y

RUN echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] http://packages.cloud.google.com/apt cloud-sdk main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list && curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key --keyring /usr/share/keyrings/cloud.google.gpg  add - && apt-get update -y && apt-get install google-cloud-cli -y
