FROM mcr.microsoft.com/devcontainers/python:1-3.9-bullseye

RUN curl https://get.modular.com | \
  MODULAR_AUTH=my_modular_auth_secret \
  sh -

RUN modular install mojo

RUN echo 'export MODULAR_HOME="$HOME/.modular"' >> ~/.bashrc
RUN echo 'export PATH="$MODULAR_HOME/pkg/packages.modular.com_mojo/bin:$PATH"' >> ~/.bashrc

RUN pip install --upgrade pip && pip install folium